In [1]:
import numpy as np

import matplotlib.pyplot as plt


In [2]:


def get_susceptibility(filename, N, snapshot_count, T_count):
    temps = np.load(filename)
    susceptibility = np.zeros(T_count)
    temp_count = 0
    for _, temp in temps.items():
        mag_config = np.zeros(snapshot_count)
        snap_count = 0
        for snap in temp:
            mag_config[snap_count] = np.mean(snap)
            snap_count += 1
        susceptibility[temp_count] = np.var(mag_config) / T_list[temp_count]
        temp_count += 1
    return susceptibility


In [7]:
snapshot = np.load("data_40.npz")
f = snapshot.files

In [34]:
    sp =snapshot['arr_39']
    print(sp[39])
    ssp = np.array(sp)
    ssp[39].size

[[ 1  1  1 ... -1  1  1]
 [-1  1  1 ... -1  1  1]
 [ 1 -1  1 ... -1 -1  1]
 ...
 [-1  1  1 ... -1  1  1]
 [ 1  1  1 ...  1  1  1]
 [ 1 -1 -1 ...  1  1  1]]


1600

In [23]:
k =0
print(k in range(2))

True


In [19]:
    filename="data_40.npz"
    N = 40
    snapshot_count = 1000
    T_count = 40
    def ms(sn,i,j):
      s=0
      for t in range(1000): 
        s += sn[t][i][j]
      return s/1000  
    def red(tt):
     r_config = np.zeros(40)
     for i in range (40):
         r_config[k]+=tt[i][k]
     r_config[k]= r_config[k] /40
     return r_config[k]    



    temps = np.load(filename)
    
    c=0
   
    for _,temp in temps.items():
        tx= np.array(temp)
        
        snap_count = 0
        
        x=[[]*40]*40
        for k in range(40):
            for i in range(40):
                for j in range(40):
                    x[i][k]=(i-ms(tx,i,j))*(k-ms(tx,k,j))
            
        p    
        print(red(x))
            
       

IndexError: list assignment index out of range